# Generated by Django 4.1.3 on 2022-12-03 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdestinations',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 23, 48, 54, 129988)),
            preserve_default=False,
        ),
    ]
